#!/usr/bin/env python3
"""Wrap src/cl/*.cl as C++ string data -> src/bundle.cpp

This replaces gpuowl's genbundle.sh, which emits one raw string literal per .cl
file. MSVC caps a single string literal at 65535 bytes (C2026) and several
kernels are well over that -- carryfused.cl alone is ~89 KB -- so each file is
emitted as an array of chunks that are concatenated once at startup.

Usage:  python tools/genbundle.py
"""

import os, sys

CHUNK = 16384          # comfortably under the MSVC limit
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLDIR = os.path.join(HERE, 'src', 'cl')
OUT = os.path.join(HERE, 'src', 'bundle.cpp')

DELIM = 'cltag'


def main():
    names = sorted(f for f in os.listdir(CLDIR) if f.endswith('.cl'))
    if not names:
        sys.exit('no .cl files found in ' + CLDIR)

    out = []
    w = out.append
    w('// Generated by tools/genbundle.py -- do not edit.\n')
    w('// Source: src/cl/*.cl\n\n')
    w('#include <string>\n#include <vector>\n\n')
    w('namespace {\n\n')

    for i, name in enumerate(names):
        with open(os.path.join(CLDIR, name), 'rb') as f:
            data = f.read()
        if (b')' + DELIM.encode() + b'"') in data:
            sys.exit('%s contains the raw-string delimiter )%s"' % (name, DELIM))
        w('// %s (%d bytes)\n' % (name, len(data)))
        w('const char* const CHUNKS_%d[] = {\n' % i)
        for off in range(0, len(data), CHUNK):
            piece = data[off:off + CHUNK].decode('utf-8')
            w('R"%s(%s)%s",\n' % (DELIM, piece, DELIM))
        w('nullptr};\n\n')

    w('const char* const* const ALL_CHUNKS[] = {%s};\n'
      % ', '.join('CHUNKS_%d' % i for i in range(len(names))))
    w('const char* const ALL_NAMES[] = {%s};\n'
      % ', '.join('"%s"' % n for n in names))
    w('const int N_FILES = %d;\n\n' % len(names))

    w('''struct Bundle {
  std::vector<std::string> texts;
  std::vector<const char*> ptrs;
  std::vector<const char*> names;

  Bundle() {
    for (int i = 0; i < N_FILES; ++i) {
      std::string s;
      for (const char* const* p = ALL_CHUNKS[i]; *p; ++p) { s += *p; }
      texts.push_back(std::move(s));
      names.push_back(ALL_NAMES[i]);
    }
    // Only safe once "texts" has stopped growing: push_back may reallocate.
    for (const std::string& s : texts) { ptrs.push_back(s.c_str()); }
  }
};

const Bundle& bundle() { static const Bundle b; return b; }

} // namespace

''')
    w('const std::vector<const char*>& getClFileNames() { return bundle().names; }\n')
    w('const std::vector<const char*>& getClFiles() { return bundle().ptrs; }\n')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(out))

    total = sum(os.path.getsize(os.path.join(CLDIR, n)) for n in names)
    print('bundle.cpp: %d files, %d bytes of kernel source, max chunk %d'
          % (len(names), total, CHUNK))


if __name__ == '__main__':
    main()
