#!/usr/bin/env python3
"""Check a run of the worktodo matrix generated by tools/genmatrix.py.

    python tools/genmatrix.py accept
    ./Mp_p-1_gpu > run.log 2>&1
    python tools/checkmatrix.py accept [--exe ./Mp_p-1_gpu] [--log run.log]

Compares every results.txt line against the predicted status, factor set and
field set; asserts a set of log properties; and then feeds each REJECT line
through the program one at a time, since the queue is fail-fast and a bad line
cannot share a file with good ones.

Exit status is 0 only if everything matched.
"""
import json
import os
import re
import subprocess
import sys

def top_keys(raw):
    """Top-level JSON keys, in order. A hand scanner rather than a parser: the
    field ORDER is part of what is under test, and json.loads would discard
    it."""
    keys, depth, in_str, esc, cur = [], 0, False, False, ""
    for i, c in enumerate(raw):
        if in_str:
            if esc:            esc = False
            elif c == "\\":    esc = True
            elif c == '"':
                in_str = False
                j = i + 1
                while j < len(raw) and raw[j] in " \t":
                    j += 1
                if depth == 1 and j < len(raw) and raw[j] == ":":
                    keys.append(cur)
            else:              cur += c
            continue
        if c == '"':                in_str, cur = True, ""
        elif c in "{[":             depth += 1
        elif c in "}]":             depth -= 1
    return keys

# stage2-fft-length is NOT here: 1.9.5 emits it, on the same P-1 stage-2 lines
# that carry "d". poly1-size and poly2-size stay forbidden -- they size
# polynomials this program never builds, so any value would be invented.
FORBIDDEN = ("security-code", "poly1-size", "poly2-size",
             "build", "port", "seed")

def job_resolutions(log):
    """What each job actually resolved factored_to and bias to, in order.
    The startup line is the only place they are visible, and they are the two
    scalars a worktodo line can override, so reading them back is how the
    precedence chain gets checked rather than assumed."""
    pat = r"^\s*M\d+, trial-factored to (\d+) bits, bias ([\d.]+)"
    return [(int(a), float(b)) for a, b in re.findall(pat, log, re.M)]

def check_results(cases, log):
    raws = [l.strip() for l in open("results.txt") if l.strip()]
    got  = [json.loads(l) for l in raws]
    fails = []
    if len(got) != len(cases):
        fails.append((0, f"{len(got)} result lines for {len(cases)} entries", []))
    for i, (e, g, raw) in enumerate(zip(cases, got, raws), 1):
        prob = []
        if e["worktype"] != "both" and g["worktype"] != e["worktype"]:
            prob.append(f'worktype {g["worktype"]} != {e["worktype"]}')

        if e["predict"]:
            want = sorted(e["factors"], key=int)
            have = sorted(g.get("factors", []), key=int)
            if want != have:
                prob.append(f"factors {have} != {want}")
            if g["status"] != ("F" if want else "NF"):
                prob.append(f'status {g["status"]}')

        has_b2, has_d, has_start = "b2" in g, "d" in g, "start" in g
        if e["predict"]:
            if has_b2 != e["ran_stage2"]:
                prob.append(f"b2 present={has_b2}, expected {e['ran_stage2']}")
            if has_d != (e["ran_stage2"] and g["worktype"] == "P-1"):
                prob.append(f"d present={has_d}")
        if has_d and g["worktype"] == "P+1":
            prob.append("P+1 carries d")
        if has_b2 != has_d and g["worktype"] == "P-1" and e["predict"]:
            prob.append("b2 and d disagree")
        if has_start != (g["worktype"] == "P+1"):
            prob.append(f"start present={has_start} on {g['worktype']}")

        if ("aid" in g) != e["aid"]:
            prob.append(f'aid present={"aid" in g}')
        if ("known-factors" in g) != bool(e["known"]):
            prob.append(f'known-factors present={"known-factors" in g}')
        elif e["known"] and g["known-factors"] != e["known"]:
            prob.append(f'known-factors {g["known-factors"]}')

        if g["b1"] != e["b1"]:
            prob.append(f'b1 {g["b1"]} != {e["b1"]}')
        if has_b2 and e["predict"] and g["b2"] != e["b2"]:
            prob.append(f'b2 {g["b2"]} != {e["b2"]}')

        for bad in FORBIDDEN:
            if bad in g:
                prob.append(f"emitted {bad}")
        if "fft-length" not in g:
            prob.append("no fft-length")

        # stage2-fft-length rides with "d": P-1, and only when stage 2 is what
        # produced the result. It must equal fft-length, because one FFT is
        # chosen per job and both stages share it -- if that ever stops being
        # true the writer is reusing a value it should be reading.
        has_s2fft = "stage2-fft-length" in g
        if has_s2fft != has_d:
            prob.append(f"stage2-fft-length present={has_s2fft}, d present={has_d}")
        elif has_s2fft and g["stage2-fft-length"] != g["fft-length"]:
            prob.append(f'stage2-fft-length {g["stage2-fft-length"]} != fft-length {g["fft-length"]}')
        if g["exponent"] != 1000273:
            prob.append(f'exponent {g["exponent"]}')

        # the two scalars a line can override, as the job actually resolved them
        res = job_resolutions(log)
        if i <= len(res):
            got_ft, got_bias = res[i - 1]
            if e.get("ft") is not None and got_ft != e["ft"]:
                prob.append(f'factored_to resolved to {got_ft}, expected {e["ft"]}')
            if e.get("bias") is not None and abs(got_bias - e["bias"]) > 1e-9:
                prob.append(f'bias resolved to {got_bias}, expected {e["bias"]}')
        else:
            prob.append("no startup line for this job")

        # B2_start is reported by a warning, or not at all
        want_warn = e.get("warn_b2start", 0)
        if want_warn and not re.search(rf"B2_start={want_warn}\b", log):
            prob.append(f"no warning for B2_start={want_warn}")

        print(f'{i:>3}  {g["status"]:3} {"".join(c for c, on in (("2",has_b2),("d",has_d),("s",has_start),("a","aid" in g),("k","known-factors" in g)) if on):<5}  {e["note"][:62]}')
        if prob:
            fails.append((i, e["line"], prob))
    return fails

def check_log(cases, log, scenario):
    """Properties of the run as a whole, not of any one line."""
    if scenario == "resume":
        # The program's own B2 extension: a completed stage-2 record being
        # reused rather than the range being re-walked. Distinct from a
        # Pminus1= line's B2_start, which is progress made elsewhere and
        # cannot be honoured at all.
        return [
            ("stage 1 reused from its checkpoint",
             log.count("already complete in pm1_1000273_b1_200.save") == 2),
            ("stage 2 extended rather than re-walked",
             "extending the completed B2=525 result to B2=2000" in log),
            ("only the uncovered range was walked",
             "204 primes in (525, 2000]" in log),
            ("the first run walked the whole of its own range",
             "53 primes in (200, 525]" in log),
            ("an identical repeat walked nothing at all",
             "already complete in pm1_1000273_s2_200_2000.save" in log),
            ("no crash and no hard failure",
             "terminate called" not in log and "FAILED" not in log),
            ("the queue drained completely", "worktodo.txt is empty" in log),
        ]
    # every B2_start that should NOT have been read
    quiet = [1500, 2000, 99999]
    warned = {int(m) for m in re.findall(r"B2_start=(\d+)", log)}
    checks = [
        ("every B2_start above B1 warned",
         all(w in warned for w in quiet)),
        ("no warning for a B2_start at or below B1",
         150 not in warned and 200 not in warned),
        ("a B2_start in the sieve_depth slot is lost, not warned",
         8000 not in warned),
        ("stage-1-only announced when B2 <= B1", "stage 2 not requested" in log),
        ("assignment tests_saved shown as the bias",
         "(the assignment's tests_saved)" in log),
        ("bias 1.0 from an assignment", "bias 1.0 (the assignment" in log),
        ("bias 100.0 from an assignment", "bias 100.0 (the assignment" in log),
        ("tests_saved 0 falls back to config", re.search(r"bias 2\.0\s*$", log, re.M) is not None),
        ("P+1 ran from 2/7", "start 2/7" in log),
        ("P+1 ran from 6/5", "start 6/5" in log),
        ("no crash and no hard failure",
         "terminate called" not in log and "FAILED" not in log),
        ("the queue drained completely", "worktodo.txt is empty" in log),
    ]
    return checks

def check_parse_ok(parse_ok, exe):
    """Valid but too costly to run: assert only that they parse and choose."""
    fails = []
    for note, line in parse_ok:
        with open("worktodo.txt", "w", newline="") as f:
            f.write(line + "\r\n")
        out = subprocess.run([exe, "--bounds"], capture_output=True, text=True,
                             timeout=300).stdout
        err = re.search(r"^(worktodo\.txt line \d+: .*)$", out, re.M)
        ran = re.search(r"^\s*M\d+, trial-factored", out, re.M)
        ok = bool(ran) and not err
        print(f'  {"ok " if ok else "BAD"}  {note:<40} '
              f'{err.group(1)[:70] if err else "parsed"}')
        if not ok:
            fails.append((0, line, ["should have parsed: " + note]))
    return fails

def check_rejects(reject, exe):
    """Each must be refused, with a diagnostic naming the problem."""
    fails = []
    for note, line in reject:
        with open("worktodo.txt", "w", newline="") as f:
            f.write(line + "\r\n")
        out = subprocess.run([exe, "--bounds"], capture_output=True, text=True,
                             timeout=300).stdout
        err = re.search(r"^(worktodo\.txt line \d+: .*)$", out, re.M)
        ran = re.search(r"^\s*M\d+, trial-factored", out, re.M)
        ok = bool(err) and not ran
        print(f'  {"ok " if ok else "BAD"}  {note:<38} {err.group(1)[:74] if err else "ACCEPTED"}')
        if not ok:
            fails.append((0, line, ["should have been refused: " + note]))
    return fails

def main():
    scenario = sys.argv[1] if len(sys.argv) > 1 else "accept"
    exe = "./Mp_p-1_gpu.exe" if os.path.exists("./Mp_p-1_gpu.exe") else "./Mp_p-1_gpu"
    logfile = "run.log"
    for i, a in enumerate(sys.argv):
        if a == "--exe":  exe = sys.argv[i + 1]
        if a == "--log":  logfile = sys.argv[i + 1]

    data = json.load(open("expected.json"))
    log = open(logfile, encoding="utf-8", errors="replace").read()

    print(f"=== {scenario}: results.txt, line by line ===")
    fails = check_results(data["cases"], log)

    print("\n=== log ===")
    for name, ok in check_log(data["cases"], log, scenario):
        print(f'  {"PASS" if ok else "FAIL"}  {name}')
        if not ok:
            fails.append((0, name, ["log assertion"]))

    if scenario == "accept":
        print("\n=== valid, but too costly to run: parse only ===")
        fails += check_parse_ok(data.get("parse_ok", []), exe)
        print("\n=== inputs that must be refused (fed one at a time) ===")
        fails += check_rejects(data["reject"], exe)

    print()
    if fails:
        print(f"{len(fails)} problem(s):")
        for i, what, prob in fails:
            print(f"  {what}")
            for p in prob:
                print(f"      {p}")
    else:
        print(f"all {len(data['cases'])} lines, every log assertion, and "
              f"{len(data['reject']) if scenario == 'accept' else 0} refusals: OK")
    return 1 if fails else 0

if __name__ == "__main__":
    sys.exit(main())
